version: "3.4"

x-common: &common
  restart: unless-stopped
  volumes:
    - ./data/.opencanary.conf:/root/.opencanary.conf
    # uncomment below if running Samba
    # - /var/log/samba-audit.log:/var/log/samba-audit.log
  image: "opencanary"
  #network_mode: "host"
  #ports:
    # Comment/un-comment the port lines below to disable/enable the services you are using
    # FTP
    # - "21:21"
    # SSH
    # - "22:22"
    # Telnet
    # - "23:23"
    # TFTP
    # - "69:69"
    # HTTP
    #- "80:80"
    # NTP
    # - "123:123"
    # SNMP
    # - "161:161"
    # MSSQL
    # - "1433:1433"
    # MYSQL
    # - "3306:3306"
    # RDP
    # - "3389:3389"
    # VNC
    # - "5000:5000"
    # SIP
    # - "5060:5060"
    # REDIS
    # - "6379:6379"
    # TCP Banner
    # - "8001:8001"
    # HTTP Proxy
    # - "8080:8080"
    # Git
    # - "9418:9418"
services:
  opencanary1:
    <<: *common
    container_name: opencanary_${CONTAINER_NAME}
    mac_address: "${MAC_ADDRESS}"
    networks:
      my_custom_network:
        ipv4_address: "${IP_ADDRESS}"
    build:
      context: .
      dockerfile: Dockerfile.latest 
    ports:
      - "${HTTP_PORT}:80"
      - "21:21"

  # opencanary2:
  #   <<: *common
  #   container_name: opencanary2
  #   mac_address: "02:42:ac:11:00:02"
  #   networks:
  #     my_custom_network:
  #       ipv4_address: 192.168.1.102
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.latest 
  #   ports:
  #     - "8081:80"

networks:
  my_custom_network:
    external: false
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24

